### ISSUE TITLE
Sometimes bosses spawns with very little health

### ISSUE THREAD

**Issue by ZonK256** [PlexusDuMenton/RandomSpices#2]
When it happens, game is throwing exceptions like crazy and runs at ~2 fps

> **[Error  : Unity Log]** NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlexusUtils.ModRecalculate.ModdedRecalculate (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody character) (at <44d659d247ba40efbe9500595c747c2c>:0)
DMD<>?-68872192._Hook<RoR2_CharacterBody::RecalculateStats>?-1736131072 (RoR2.CharacterBody ) (at <96a74e2c80aa43e5a9ad68ecedde8657>:0)
RoR2.CharacterMaster.OnBodyStart (RoR2.CharacterBody body) (at <589195a5bfc3458a82af46bd6c8ea5ac>:0)
RoR2.CharacterBody.UpdateMasterLink () (at <589195a5bfc3458a82af46bd6c8ea5ac>:0)
RoR2.CharacterBody.FixedUpdate () (at <589195a5bfc3458a82af46bd6c8ea5ac>:0)

**Comment by PlexusDuMenton** [comment]
hm, any additional information, like the context ? how reproductable is it ? ^^

Because actualy it's sound closer to be ModRecalculate issue (which is by me, so it's still revelent no worry)

**Comment by ZonK256** [comment]
Unfortunately, I didn't figure out any pattern to reproduce it yet (the only thing I noticed is that is more likely to happen in later stages). Issue occurs both on shrine bosses and "natural spawning" ones. Will provide more information when possible.

**Comment by PlexusDuMenton** [comment]
Here a list of question : 
Does it happen ONLY in late game ? 
Does Montain Shrine increase the possibility ? 
If it happen once, does it allways happen ? 
Does it only happen on Boss ? 
Does boss elite are more likely than normal boss ? 
What are the boss health value before this bug happen ?

**Comment by ZonK256** [comment]
Coming back after more testing. So from my investigations:
Does it happen ONLY in late game ? -> I managed to spawn first boss with 100 hp in first stage, but it was only when I was intentionally messing with game (adding 9999999 gold/ a lot of syringes / switching to immortality)
Does Montain Shrine increase the possibility ? -> yes, more healthy bosses were more likely to break
If it happen once, does it allways happen ? ->  In later game, yes. In the run above (with 2,1k health boss) later bosses spawned normally
Does it only happen on Boss ? yes
Does boss elite are more likely than normal boss ? no
What are the boss health value before this bug happen ? in normal run bosses start to break at ~322k hp

Additional info: 

- In all my runs Stone Titans were always the first ones, which spawned with broken hp.
- Broken bosses are passive

![image](https://user-images.githubusercontent.com/25548445/57165866-9aec3880-6df8-11e9-8e18-8923ea8ed3e7.png)

**Comment by PlexusDuMenton** [comment]
What is your mod list ?
also, if you disable RandomSpice (but keep ModRecalculate, does it keep hapening ?)

Edit : 
If it's still happen without RandomSpice, I'll give you an update version of ModRecalculate to test

**Comment by ZonK256** [comment]
Later on I disabled other mods, so besides your 2 the only additional was RoR2Cheats. 

I'm seeing that you updated ModRecalculate meanwhile, so I'm gonna use the newer version without RandomSpice.

**Comment by ZonK256** [comment]
Can confirm that bug still occurs on newest version of ModRecalculate without RandomSpieces.
It looks like Stone Titans are always broken. I spawned one of them and it has around 3/5 hp. I also got ~5 fps when opening console.

![image](https://user-images.githubusercontent.com/25548445/57175677-e9c4bd00-6e4e-11e9-9255-b674ec38b936.png)

**Comment by PlexusDuMenton** [comment]
Could you replace ModRecalculate with this one : 

[ModRecalculate.zip](https://github.com/PlexusDuMenton/RandomSpices/files/3144499/ModRecalculate.zip)

it may not fix the issue but on error will log information to help me

**Comment by ZonK256** [comment]
Current error log:
> **[Error  : Unity Log]** NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlexusUtils.ModRecalculate.ModdedRecalculate (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody character) (at <8928af89d34943a4bc344ee256799523>:0)
DMD<>?-570987520._Hook<RoR2_CharacterBody::RecalculateStats>?-1144821504 (RoR2.CharacterBody ) (at <2a92249190d7480da2a4f433b02e36a2>:0)
RoR2.CharacterBody.Start () (at <589195a5bfc3458a82af46bd6c8ea5ac>:0)
**[Error  : Unity Log]** NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlexusUtils.ModRecalculate.ModdedRecalculate (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody character) (at <8928af89d34943a4bc344ee256799523>:0)
DMD<>?-570987520._Hook<RoR2_CharacterBody::RecalculateStats>?-1144821504 (RoR2.CharacterBody ) (at <2a92249190d7480da2a4f433b02e36a2>:0)
RoR2.CharacterMaster.OnBodyStart (RoR2.CharacterBody body) (at <589195a5bfc3458a82af46bd6c8ea5ac>:0)
RoR2.CharacterBody.UpdateMasterLink () (at <589195a5bfc3458a82af46bd6c8ea5ac>:0)
RoR2.CharacterBody.FixedUpdate () (at <589195a5bfc3458a82af46bd6c8ea5ac>:0)

**Comment by PlexusDuMenton** [comment]
still the same, I'll try to move the log a bit deeper into the code ...

Try this : 
[ModRecalculate.zip](https://github.com/PlexusDuMenton/RandomSpices/files/3144593/ModRecalculate.zip)

**Comment by PlexusDuMenton** [comment]
Nop,e issue still exist I'll do many bug test to pin points location on my side, also, now I'll use this issue : 
https://github.com/PlexusDuMenton/ModRecalculate/issues/3
